
[AtCoder]
  ContestID = "abc176"
  ContestURL = "https://atcoder.jp/contests/abc176"
  TaskID = "abc176_e"
  TaskName = "E - Bomber"
  TaskURL = "https://atcoder.jp/contests/abc176/tasks/abc176_e"

[Environment]
  BuildCmd = ""
  BuildCmdOnDocker = ""
  CleanCmd = ""
  Cmd = "python3 -B main.py"
  CmdOnDocker = "python -B main.py"
  DockerImage = "docker.io/sachaos/atcoder-python3:latest"
  Key = "python3"
  Language = "Python3 (3.8.2)"
  LanguageCode = "4006"
  Note = ""
  SrcName = "main.py"
  Template = "internal/python3/main.py"
