
[AtCoder]
  ContestID = "abc177"
  ContestURL = "https://atcoder.jp/contests/abc177"
  TaskID = "abc177_e"
  TaskName = "E - Coprime"
  TaskURL = "https://atcoder.jp/contests/abc177/tasks/abc177_e"

[Environment]
  BuildCmd = ""
  BuildCmdOnDocker = ""
  CleanCmd = ""
  Cmd = "python3 -B main.py"
  CmdOnDocker = "python -B main.py"
  DockerImage = "docker.io/sachaos/atcoder-python3:latest"
  Key = "python3"
  Language = "Python3 (3.8.2)"
  LanguageCode = "4006"
  Note = ""
  SrcName = "main.py"
  Template = "internal/python3/main.py"
