
[AtCoder]
  ContestID = "abc164"
  ContestURL = "https://atcoder.jp/contests/abc164"
  TaskID = "abc164_d"
  TaskName = "D - Multiple of 2019"
  TaskURL = "https://atcoder.jp/contests/abc164/tasks/abc164_d"

[Environment]
  BuildCmd = ""
  BuildCmdOnDocker = ""
  CleanCmd = ""
  Cmd = "python3 -B main.py"
  CmdOnDocker = "python -B main.py"
  DockerImage = "docker.io/sachaos/atcoder-python3:latest"
  Key = "python3"
  Language = "Python3 (3.8.2)"
  LanguageCode = "4006"
  Note = ""
  SrcName = "main.py"
  Template = "internal/python3/main.py"
