
[AtCoder]
  ContestID = "abc165"
  ContestURL = "https://atcoder.jp/contests/abc165"
  TaskID = "abc165_c"
  TaskName = "C - Many Requirements"
  TaskURL = "https://atcoder.jp/contests/abc165/tasks/abc165_c"

[Environment]
  BuildCmd = ""
  BuildCmdOnDocker = ""
  CleanCmd = ""
  Cmd = "python3 -B main.py"
  CmdOnDocker = "python -B main.py"
  DockerImage = "docker.io/sachaos/atcoder-python3:latest"
  Key = "python3"
  Language = "Python3 (3.8.2)"
  LanguageCode = "4006"
  Note = ""
  SrcName = "main.py"
  Template = "internal/python3/main.py"
