
[AtCoder]
  ContestID = "abc167"
  ContestURL = "https://atcoder.jp/contests/abc167"
  TaskID = "abc167_e"
  TaskName = "E - Colorful Blocks"
  TaskURL = "https://atcoder.jp/contests/abc167/tasks/abc167_e"

[Environment]
  BuildCmd = ""
  BuildCmdOnDocker = ""
  CleanCmd = ""
  Cmd = "python3 -B main.py"
  CmdOnDocker = "python -B main.py"
  DockerImage = "docker.io/sachaos/atcoder-python3:latest"
  Key = "python3"
  Language = "Python3 (3.8.2)"
  LanguageCode = "4006"
  Note = ""
  SrcName = "main.py"
  Template = "internal/python3/main.py"
