
[AtCoder]
  ContestID = "abc172"
  ContestURL = "https://atcoder.jp/contests/abc172"
  TaskID = "abc172_c"
  TaskName = "C - Tsundoku"
  TaskURL = "https://atcoder.jp/contests/abc172/tasks/abc172_c"

[Environment]
  BuildCmd = ""
  BuildCmdOnDocker = ""
  CleanCmd = ""
  Cmd = "python3 -B main.py"
  CmdOnDocker = "python -B main.py"
  DockerImage = "docker.io/sachaos/atcoder-python3:latest"
  Key = "python3"
  Language = "Python3 (3.8.2)"
  LanguageCode = "4006"
  Note = ""
  SrcName = "main.py"
  Template = "internal/python3/main.py"
